<html lang="pt-BR">

    <head>
        <meta charset="UTF-8">
        <meta name="viewport"
              content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
        <meta http-equiv="X-UA-Compatible" content="ie=edge">

        <meta http-equiv="content-type" content="text/html;charset=utf-8"/>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="description" content="SECTIDS MaInE - Mapa de Informações Estratégicas">
        <meta name="viewport" content="width=device-width, initial-scale=1.0, minimum-scale=1.0">
        <title>Maine</title>

        <!-- Add to homescreen for Chrome on Android -->
        <meta name="mobile-web-app-capable" content="yes">
        <link rel="icon" sizes="192x192" href="<?php echo CAMINHO_SITE_ROOT; ?>images/android-desktop.png">

        <!-- Add to homescreen for Safari on iOS -->
        <meta name="apple-mobile-web-app-capable" content="yes">
        <meta name="apple-mobile-web-app-status-bar-style" content="black">
        <meta name="apple-mobile-web-app-title" content="Material Design Lite">
        <link rel="apple-touch-icon-precomposed"
              href="<?php echo CAMINHO_SITE_ROOT; ?>images/ios-desktop.png">

        <!-- Tile icon for Win8 (144x144 + tile color) -->
        <meta name="msapplication-TileImage"
              content="<?php echo CAMINHO_SITE_ROOT; ?>images/touch/ms-touch-icon-144x144-precomposed.png">
        <meta name="msapplication-TileColor" content="#3372DF">

        <!--        <link rel="shortcut icon" href="--><?php //echo CAMINHO_SITE_ROOT; ?><!--app.webroot/images/favicon.png">-->
        <link rel="shortcut icon" href="http://www.rj.gov.br/html/themes/woden-main/images/liferay.ico">

        <!-- SEO: If your mobile URL is different from the desktop URL, add a canonical link to the desktop page https://developers.google.com/webmasters/smartphone-sites/feature-phones -->
        <!--
        <link rel="canonical" href="http://www.example.com/">
        -->

        <!-- styles -->
        <link rel="stylesheet"
              href="https://fonts.googleapis.com/css?family=Roboto:regular,bold,italic,thin,light,bolditalic,black,medium&amp;lang=en">
        <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
        <link rel="stylesheet" href="<?php echo CAMINHO_SITE_ROOT; ?>css/libs/dialog-polyfill.css">
        <link rel="stylesheet" href="https://code.getmdl.io/1.3.0/material.indigo-pink.min.css">
        <link rel="stylesheet" href="<?php echo CAMINHO_SITE_ROOT; ?>css/libs/mdl-ext-eqjs.min.css">


        <link rel="stylesheet" href="<?php echo CAMINHO_SITE_ROOT; ?>css/mdl/styles.css">

        <link rel="stylesheet" href="<?php echo CAMINHO_SITE_ROOT; ?>css/style.css">

        <!--Estilizacao dos itens do Google Maps-->

        <!--Scroll Custom-->
        <link rel="stylesheet"
              href="<?PHP echo CAMINHO_SITE_ROOT; ?>js/libs/scrollbarPluginJquery/jquery.mCustomScrollbar.css">



        <!--CAMINHOS BASE DO PHP SITE-->
        <input type="hidden" value="<?php echo CAMINHO_SITE_ROOT; ?>" id="url_base">

        <!--CARREGAMENTO DE SCRIPTS-->

        <!-- JavaScript -->
        <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
        <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
        <!--[if lt IE 9]>
        <!--<script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>-->
        <!--            <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>-->
        <!--            <![endif] -->


        <!-- Scripts -->
        <!--Polyfill Fix-->
        <script src="<?php echo CAMINHO_SITE_ROOT; ?>js/libs/dialog-polyfill.js" type="text/javascript"
                charset="utf-8"></script>
        <script src="https://cdn.polyfill.io/v2/polyfill.min.js?features=default,es6"></script>

        <!--Plugins - [FastClick.js | Material.js] -->
        <script type="text/javascript" src="<?php echo CAMINHO_SITE_ROOT ?>js/plugins.js"></script>

        <!--Script Base do FrontEnd-->
        <script type="text/javascript" src="<?php echo CAMINHO_SITE_ROOT; ?>js/main.js"></script>

    </head>

    <body>

        <header></header>

        <aside></aside>

        <!------------------------------------------------------------->
        <!--CONTROLLER - INCLUSAO DO CONTROLLER RESPONSAVEL          -->
        <!------------------------------------------------------------->
        <main class="mdl-layout__content mdl-color--grey-100">

            <?php echo $this->content(); // Content do CONTROLLER ?>

        </main>
        <!------------------------------------------------------------->
        <!------------------------------------------------------------->
        <!------------------------------------------------------------->


        <!--Tela de Carregamento - BlackScreen - Loading-->
        <link href="<?PHP echo CAMINHO_SITE_ROOT; ?>css/blackScreenLoading.css" rel="stylesheet"/>
        <div id="loader-wrapper" style="display: none">
            <div id="loader"></div>
            <div class="loader-section section-left"></div>
            <div class="loader-section section-right"></div>
        </div>

    </body>

</html>